# fly.toml app configuration file generated for oxeldev on 2023-05-02T14:30:16+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oxeldev"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"
processes = []

# [build]
# 
# [env]
# 
# [experimental]
#   auto_rollback = true
# 
# [[services]]
#   http_checks = []
#   internal_port = 4443
#   processes = ["app"]
#   protocol = "tcp"
#   script_checks = []
#   [services.concurrency]
#     hard_limit = 25
#     soft_limit = 20
#     type = "connections"
# 
#   [[services.ports]]
#     force_https = true
#     handlers = ["http"]
#     port = 80
# 
#   [[services.ports]]
#     handlers = ["tls", "http"]
#     port = 443
# 
#   [[services.tcp_checks]]
#     grace_period = "1s"
#     interval = "15s"
#     restart_limit = 0
#     timeout = "2s"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8043
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
